### ISSUE TITLE
Exception when trying update JarContainer

### ISSUE THREAD

**Issue by vitekkor** [vorpal-research/kfg#12]
``` kotlin
fun createKFGGraphs(jars: List<Container>): MutableMap<String, MutableList<Graph>> {
        log.info("Creating CGF for $containers")
        val kfgGraphs = mutableMapOf<String, MutableList<Graph>>()
        for (jar in jars) {
            val cm = ClassManager(KfgConfig(Flags.readAll, failOnError = true))
            cm.initialize(jar)
            val graphs = mutableListOf<Graph>()
            for (klass in cm.concreteClasses) {
                for (method in klass.allMethods) {
                    if (!method.isNative)
                        graphs.add(method.toGraph(method.name + "::" + method.prototype.replace("/", ".")))
                }
            }
            kfgGraphs[jar.name] = graphs
            jar.update(cm, jar.path, jar.classLoader)
        }
        return kfgGraphs
    }
```
Вылетает exception при попытке создать cfg как описано в readme:
``` java
Exception in thread "main" java.io.FileNotFoundException: D:\IdeaProjects\kex\kex-test-0.0.1-jar-with-dependencies.jar\kex-test-0.0.1-jar-with-dependencies.jar (Системе не удается найти указанный путь)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:126)
	at org.jetbrains.research.kfg.util.JarBuilder.<init>(jar.kt:105)
	at org.jetbrains.research.kfg.container.JarContainer.update(JarContainer.kt:115)
	at org.jetbrains.research.kfg.container.JarContainer.update(JarContainer.kt:18)
```

При отладке выяснил, что проблема где-то [здесь](https://github.com/vorpal-research/kfg/blob/a79e2fb1dd6052bc947e19636a79fea63845eb41/src/main/kotlin/org/jetbrains/research/kfg/container/JarContainer.kt#L112)
``` kotlin
val absolutePath = target.toAbsolutePath()
val jarName = file.name.substringAfterLast(File.separator).removeSuffix(".jar")
val jarPath = absolutePath.resolve("$jarName.jar")
val builder = JarBuilder("$jarPath", manifest)
```
В `absolutePath` у меня `D:\IdeaProjects\kex\kex-test-0.0.1-jar-with-dependencies.jar`, а в `jarPath`, который потом в `JarBuilder` передаётся, `D:\IdeaProjects\kex\kex-test-0.0.1-jar-with-dependencies.jar\kex-test-0.0.1-jar-with-dependencies.jar`, что кажется очень странным

**Comment by AbdullinAM** [comment]
Вы правильно обнаружили что ошибка вылетает при вызове метода `jar.update`. В readme сейчас указан ненекорректный пример. Начиная с версии 0.0.14 метод `jar.update` принимает на вход три аргумента:
* `ClassManager`, в котором инициализирован этот jar
* путь к директории, в которой будет создана новая версия контейнера с обновленными классами
* `ClassLoader` опцинально

Т.е. `jar.update` **не изменяет** оригинальный контейнер, а создает его обновленную копию. Путь нужно тоже указывать не к оригинальному контейнеру, а, например, к какой-либо пустой директории (замечу что предварительно будут записаны все классы, содержащиеся в контейнере (примерно как это выглядит в `target/classes` при сборке через maven)

Я обновлю описания и readme, спасибо
